#!/bin/bash

# Create the new database and user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER '$POSTGRES_DIRECTUS_USER' WITH PASSWORD '$POSTGRES_DIRECTUS_PASSWORD';
    CREATE DATABASE '$POSTGRES_DIRECTUS_DATABASE' OWNER '$POSTGRES_DIRECTUS_USER';
EOSQL

echo "Database '$POSTGRES_DIRECTUS_DATABASE' and user '$POSTGRES_DIRECTUS_USER' created successfully!"
